args:
  cloud-provider: libvirt
  allow-untagged-cloud: ""

kind: Deployment
replicaCount: 1
env:
  LIBVIRT_URI:
    valueFrom:
      secretKeyRef:
        name: libvirt
        key: uri
  # Uncomment to enable debug logs for libvirt calls. Possible values are:
  # 1: DEBUG
  # 2: INFO
  # 3: WARNING
  # 4: ERROR
  # LIBVIRT_DEBUG:
  #   value: 4
  # Uncomment to enable debug logs for the cloud controller manager.
  # DEBUG:
  #   value: "true" 
  # Uncomment to enbable Metrics
  # METRICS_ENABLED:
  #  value: "true"
  # METRICS_ADDR:
  #   value: ":8233"
image:
  repository: ghcr.io/ajquack/libvirt-cloud-controller-manager
  tag: "v{{ $.Chart.Version }}"

monitoring:
  enabled: true
  podMonitor:
    enabled: false
    labels: {}
    annotations: {}
    spec:
      podMetricsEndpoints:
        - port: metrics
nameOverride: ~

resources:
  requests:
    cpu: 100m
    memory: 50Mi

selectorLabels:
  app.kubernetes.io/name: '{{ include "libvirt-cloud-controller-manager.name" $ }}'
  app.kubernetes.io/instance: "{{ $.Release.Name }}"


additionalTolerations: []

# nodeSelector:
#   node-role.kubernetes.io/control-plane: ""
nodeSelector: {}

# Set the affinity for pods. (Only works with kind=Deployment)
affinity: {}

podLabels: {}

podAnnotations: {}

# Mounts the specified volume to the hcloud-cloud-controller-manager container.
extraVolumeMounts: []

# Adds extra volumes to the pod.
extraVolumes: []